import { createStore } from "vuex";

const store = createStore({
  state: {
    txt: {
      language: "English",
      Choose: "Please select language",
      continue: "continue",
      cjpassword:
        "Please create a password, including the following conditions",
      passwordshow: "show",
      inppassword: "password",
      cfinppassword: "Repeat password",
      passwordnone: "hide",
      passlist: ["8 characters", "capital", "number", "lower case"],
      policy: "Privacy Policy",
      policyend: "scroll to bottom",
      accept: "accept",
      terms: "Terms of Service",
      forget: "forget the password",
      forgetjs:
        "Within 24 hours after changing your password, you will not be able to withdraw money on the new device.",
      setpass: "reset Password",
      gologin: "Return to login",
      enteremail: "Enter your email address",
      emailjc: "Please check your email for a password reset link",
      connectti: "Stay connected with push notifications!",
      connectjs:
        "By enabling push notifications, you will receive important updates about your transactions, MoonDrop and other important alerts and news.",
      connectbuty: "enable",
      connectbutt: "Skip for now",
      setemali: "email",
      setusername: "username",
      changeemail: "Change email",
      changeusername: "Change username",
      changepassword: "Change password",
      setyy: "language",
      setterms: "terms",
      setpolicy: "policy",
      logout: "Sign out",
      removename: "Delete your account",
      forgetpass: "forget the password",
      setfh: "return",
      nativetitle: "Get native App",
      nativecon: "Sloppy on road apps",
      welcomebutone: "Login",
      welcomebuttwo: "start using",
      logintit: "Login",
      logintitt: "Sign up",
      loginemail: "e-mail",
      loginpass: "password",
      loginnonull: "password can not be blank",
      loginbut: "Login",
      loginforget: "Forgot password",
      registerti: "Let's start",
      registercont: "What's your e-mail address?",
      registeremailadd: "email address",
      registeremailtxt: "This email will be used to log in",
      usertit: "Create username",
      usertittxt: "Username will be used as your code to refer friends?",
      userplace: "Enter your user name",
      usercont:
        "The account name should be between 4 and 22 characters, consisting only of English letters and numbers",
      recommendtit: "Do you have a referral code?",
      recommendplace: "Referral code",
      recommendcon:
        "Get a referral code and get a $25 bonus to cover future expenses",
      recommendbutone: "Submit code",
      recommendbuttwo: "jump over",
      settitle: "Profile settings",
      changeemail: "Change email",
      changeemailcon:
        "You will not be able to withdraw funds using your new device for 24 hours after changing your email address.",
      changeemailplacey: "Enter new email address",
      changeemailplacet: "Enter your password",
      changeusertity: "Change email",
      changeuserplacey: "Enter your email",
      changeuserplacet: "Enter new username",
      changeusercon:
        "Username should be between 4 and 22 characters, consisting of English letters and numbers only",
      changepasstit: "change password",
      removeusertit: "This will delete your account",
      removeuserbutyi: "Yes, delete my account",
      removeuserbutt: "Cancel",
      hometit: "Position",
      homeck: "View transactions",
      hometime: "past 24 hours",
      hometaby: "1D",
      hometabw: "1Y",
      homepower: "purchasing power",
      homefory: "trade",
      homefort: "attack",
      homeforthr: "Pre-sale",
      homeforf: "Automatic DCA",
      homeforw: "options",
      homeforsix: "wallet",
      homethrti: "Active trading",
      homethrtype: "Type",
      homethrtypey: "profit",
      homethrtypet: "loss",
      homethrtypethr: "position",
      homethrtypef: "date",
      tradey: "market",
      tradet: "trade",
      tradethr: "index",
      tradeplace: "Search coins",
      tradeinptxt: "Paste",
      tradetoptxt: "All",
      tradeinptopy: "Name/Market value",
      tradeinptopt: "price/quantity",
      givemoney: "Give a friend $25",
      tradeethbuty: "to exchange",
      tradeethbutt: "limit order",
      tradetabty: "exchange",
      tradetabtwoy: "use. . . pay",
      tradetabtwoqc: "Clear",
      tradetabtwoye: "Balance",
      teadetabtwoxd: "Max limit",
      tradetabtwosd: "receive",
      tradetabtwoty: "purchase",
      tradetabtwott: "Sell",
      tradetabtwozf: "pay",
      tradetabtwoinpy: "buy at this price",
      tradetabtwoinpt: "quantity",
      tradetabtwoinpthr: "total amount",
      tradetabtwoinpf: "Benefited from",
      tradetabtwoinpw: "stop loss",
      tradetabtwoinpsix: "The order expiry date is",
      tradetabtwopy: "Market price: 1 WETH = 1796 USDT",
      tradetabtwopt: "Set trading strategy (take profit/stop loss)",
      tradetabtwobut: "Trading",
      tradetabthrtxt: "coming soon",
      attacktit: "attack trade",
      attacktaby: "sandwich",
      attacktabt: "SniperDEX LP",
      attackonetaby: "Token",
      attacktwotaby: "Set up",
      attackonetabt: "Position",
      attackonetabthr: "History",
      attackoneyabytxt: "Deposit code to start sandwich trading",
      attackoneyabttxt: "You have no active sandwich transactions",
      attackoneyabthrtxt: "Choose a token to start the attack. >",
      attackoneyabtatxt: "You don't have any sandwich history",
      attackoneyabthratxt: "Start sandwich>",
      attacktwobuty: "custom token",
      attacktwobutt: "Snipe all",
      attavktwoinpy: "search token",
      attavktwoinpt: "Paste",
      attacktwoinpp: "How many tokens are needed for a single sniper shot?",
      attacktwoinpt: "block delay",
      attacktwoinpthr: "Gas options",
      attackbotbut: "Confirm sniper automation",
      attacktwotabery: "You have no active sniping position.",
      attacktwotabert: "Choose a token to start sniping. >",
      attacktwotabethry: "You don't have any sniping history",
      attacktwotabthrt: "Start sniping>",
      ethree: "Fees owed",
      connectlistt: "Activity",
      connecttc: "Filter",
      connecttcly: {
        one: "All",
        two: "Trade",
        three: "Attack",
        four: "Pre-sale",
      },
      connecttclt: {
        one: "All",
        two: "To-do",
        three: "Fully",
        four: "Created",
        five: "Cancel",
        six: "Failure",
      },
      connectthr: "date",
      connectfour: "reset",
      connectfive: "Apply filter",
      connectsix: "extract",
      connectqi:
        " There is no activity for trading yet, you can view it this time",
      connectba: "withdraw",
      connectjiu: "Enter public address",
      earntit: "earn",
      earntaby: "recommender",
      earntabytop: "Available rewards",
      earntabytopt: "receive",
      earntabytxt: "Commission (pledge to increase commission rate)",
      earntabttxty: "pledge",
      earntabttxtt: "(coming soon)",
      earntabthrtxty: "Estimated revenue per 1 commission",
      earntabythr: "Invite friends",
      earnrabyfour: "invite",
      earnrabyfive: "award",
      earntabtyi: "your points",
      earntabter: "you are on the leaderboard",
      earntabtsan: "get promoted",
      earntabtfour: "Token empowerment",
      earntabtfive: "Complete today's daily tasks",
      earntabtsix: "Daily boost activation:",
      earntabtqi: "Mission promotion is activated:",
      earntabtba: "Total improvement:",
      earntabtjiu: "Inactive",
      earntabtten: "Accumulate points",
      earntabttenyi: "All points received",
      earntabttener: "Ranking list",
      earntabttensan: "you are",
      earntabttenfour: "username",
      earntabttenfive: "integral",
      walletti: "Enter your recovery phrase or private key",
      walletcon:
        "Your recovery phrase or private key is required to automate transactions - capital is at risk.",
      wallettxt: "How to find my recovery phrase",
      walletplace: "Or enter a recovery message",
      walletstit: "How would you like to add your wallet?",
      walletstxty: "Import wallet",
      walletstxtt: "respected",
      walletstxtthr:
        "Enter your recovery phrase or private key from another crypto wallet",
      walletttit: "Congratulations on your new crypto wallet!",
      walletttxty: "Give your wallet a nickname.",
      walletttxtt: "My wallet 1",
      walletttxtthr: "Your public address will be",
      walletttxtf: "save this wallet",
      porttxty: "Link your wallet to get started!",
      porttxtt: "Link a new wallet",
      porttxtthr: "Link existing wallet",
      tradetctit: "Select a token",
      tradetctxty: "Search for a coin or paste the coin address",
      tradetctxtt: "Deposit tokens",
      tradetctxtthr: "Start trading",
    },

    ch: {
      language: "汉语",
      Choose: "请选择语言",
      continue: "继续",
      cjpassword: "请创建密码,包括以下条件",
      passwordshow: "展示",
      inppassword: "密码",
      cfinppassword: "重复输入密码",
      passwordnone: "隐藏",
      passlist: ["8 人物", "大写", "数字", "小写"],
      policy: "隐私政策",
      policyend: "滚动到底部",
      accept: "我接受",
      terms: "服务条款",
      forget: "忘记密码",
      forgetjs: "更改密码后24小时内,您将无法在新设备提款.",
      setpass: "重设密码",
      gologin: "返回登录",
      enteremail: "输入你的电子邮箱地址",
      emailjc: "请检查您的电子邮箱以获取密码重置链接",
      connectti: "通过推送通知保持联系!",
      connectjs:
        "通过启用推送通知, 您将收到有关您的交易、MoonDrop 的重要更新以及其他重要警报和新闻。",
      connectbuty: "使能够",
      connectbutt: "暂时跳过",
      setemali: "电子邮件",
      setusername: "用户名",
      changeemail: "更改电子邮件",
      changeusername: "更改用户名",
      changepassword: "更改密码",
      setyy: "语言",
      setterms: "条款",
      setpolicy: "政策",
      logout: "登出",
      removename: "删除您的账户",
      forgetpass: "忘记密码",
      setfh: "返回",
      nativetitle: "获取原生App",
      nativecon: "在路愿用程式上邋德",
      welcomebutone: "登录",
      welcomebuttwo: "开始使用",
      logintit: "登录",
      logintitt: "报名",
      loginemail: "电子邮件",
      loginpass: "密码",
      loginnonull: "密码不能为空",
      loginbut: "登录",
      loginforget: "忘记密码了",
      registerti: "让我们开始吧",
      registercont: "你的电子邮件地址是什么？",
      registeremailadd: "电子邮件地址",
      registeremailtxt: "该邮箱将用于登录",
      usertit: "创建用户名",
      usertittxt: "用户名将用作您推荐朋友的代码？",
      userplace: "输入用户名",
      usercont: "户名应介于4至22个字符之间，仅由英文字母和数字组成",
      recommendtit: "您有推荐码吗?",
      recommendplace: "推荐码",
      recommendcon: "获取推荐码并获得25美元的奖励以支付未来的费用",
      recommendbutone: "提交代码",
      recommendbuttwo: "跳过",
      settitle: "配置文件设置",
      changeemail: "更改电子邮件",
      changeemailcon:
        "更改电子邮件地址后 24 小时内, 您将无法使用新设备提取资金。",
      changeemailplacey: "输入新的电子邮件地址",
      changeemailplacet: "输入您的密码",
      changeusertity: "更改电子邮件",
      changeuserplacey: "输入你的邮箱",
      changeuserplacet: "输入新的用户名",
      changeusercon: "用户名应介于 4 至 22 个字符之间, 仅由英文字母和数字组成",
      changepasstit: "更改密码",
      removeusertit: "这将删除您的账户",
      removeuserbutyi: "是的, 删除我的账户",
      removeuserbutt: "取消",
      hometit: "持仓",
      homeck: "查看交易",
      hometime: "过去24小时",
      hometaby: "一维",
      hometabw: "一年",
      homepower: "购买力",
      homefory: "交易",
      homefort: "攻击",
      homeforthr: "预售",
      homeforf: "自动DCA",
      homeforw: "期权",
      homeforsix: "钱包",
      homethrti: "活跃交易",
      homethrtype: "种类",
      homethrtypey: "利润",
      homethrtypet: "损失",
      homethrtypethr: "头寸",
      homethrtypef: "日期",
      tradey: "市场",
      tradet: "交易",
      tradethr: "指数",
      tradeplace: "搜索代币",
      tradeinptxt: "粘贴",
      tradetoptxt: "全部",
      tradeinptopy: "名称/市值",
      tradeinptopt: "价格/数量",
      givemoney: "给朋友25美元",
      tradeethbuty: "去交换",
      tradeethbutt: "限价订单",
      tradetabty: "交换",
      tradetabtwoy: "使用。。。支付",
      tradetabtwoqc: "清除",
      tradetabtwoye: "余额",
      teadetabtwoxd: "最大限度",
      tradetabtwosd: "收到",
      tradetabtwoty: "买",
      tradetabtwott: "卖",
      tradetabtwozf: "支付",
      tradetabtwoinpy: "按此价格购买",
      tradetabtwoinpt: "的数量",
      tradetabtwoinpthr: "总量",
      tradetabtwoinpf: "从中受益",
      tradetabtwoinpw: "止损",
      tradetabtwoinpsix: "订单失效期为",
      tradetabtwopy: "市场价： 1 WETH = 1796 USDT",
      tradetabtwopt: "设定交易策略 （止盈/止损）",
      tradetabtwobut: "进行交易",
      tradetabthrtxt: "即将推出",
      attacktit: "攻击贸易",
      attacktaby: "三明治",
      attacktabt: "狙击DEX LP",
      attackonetaby: "代币",
      attacktwotaby: "设置",
      attackonetabt: "职位",
      attackonetabthr: "历史",
      attackoneyabytxt: "存入代码以开始夹心交易",
      attackoneyabttxt: "你没有活跃中的三明治交易",
      attackoneyabthrtxt: "选择一个代币开始攻击。>",
      attackoneyabtatxt: "你没有任何三明治历史",
      attackoneyabthratxt: "开始夹心>",
      attacktwobuty: "自定义令牌",
      attacktwobutt: "狙击全部",
      attavktwoinpy: "搜索令牌",
      attavktwoinpt: "粘贴",
      attacktwoinpp: "单次狙击需要使用多少代币",
      attacktwoinpt: "区块延迟",
      attacktwoinpthr: "气体选项",
      attackbotbut: "确认狙击自动化",
      attacktwotabery: "您没有主动狙击位置。",
      attacktwotabert: "选择一个令牌开始狙击。>",
      attacktwotabethry: "你没有任何狙击历史",
      attacktwotabthrt: "开始狙击>",
      ethree: "所欠费用",
      connectlistt: "活动",
      connecttc: "过滤器",
      connecttcly: { one: "全部", two: "交易", three: "攻击", four: "预售" },
      connecttclt: {
        one: "全部",
        two: "待办的",
        three: "完全的",
        four: "已创建",
        five: "取消",
        six: "失败的",
      },
      connectthr: "日期",
      connectfour: "重置",
      connectfive: "应用过滤器",
      connectsix: "提取",
      connectqi: " 还没有活动进行交易可以在此次查看",
      connectba: "提现",
      connectjiu: "输入公共地址",
      earntit: "赚",
      earntaby: "推荐人",
      earntabytop: "可领取的奖励",
      earntabytopt: "领取",
      earntabytxt: "佣金 (质押以提高返佣比例)",
      earntabttxty: "质押",
      earntabttxtt: "(即将推出)",
      earntabthrtxty: "每 1 佣金的预计收入",
      earntabythr: "邀请朋友",
      earnrabyfour: "邀请",
      earnrabyfive: "奖励",
      earntabtyi: "您的积分",
      earntabter: "你在排行榜上",
      earntabtsan: "获取提升",
      earntabtfour: "代币赋能",
      earntabtfive: "完成今天的每日任务",
      earntabtsix: "每日提升激活：",
      earntabtqi: "任务提升已激活：",
      earntabtba: "总提升：",
      earntabtjiu: "不活跃",
      earntabtten: "积累积分",
      earntabttenyi: "所有收到的积分",
      earntabttener: "排行榜",
      earntabttensan: "你是",
      earntabttenfour: "用户名",
      earntabttenfive: "积分",
      walletti: "输入您的恢复短语或私钥",
      walletcon: "需要您的恢复短语或私钥来实现自动化交易-资本面临风险。",
      wallettxt: "如何找到我的恢复短语",
      walletplace: "或者输入恢复短信",
      walletstit: "您想如何添加您的钱包？",
      walletstxty: "导入钱包",
      walletstxtt: "受到推崇的",
      walletstxtthr: "输入您的恢复短语或来自其他加密钱包的私钥",
      walletttit: "恭喜获得新的加密钱包!",
      walletttxty: "给你的钱包起一个昵称。",
      walletttxtt: "我的钱包1",
      walletttxtthr: "您的公共地址将是",
      walletttxtf: "保存这个钱包",
      porttxty: "链接钱包即可开始!",
      porttxtt: "链接一个新的钱包",
      porttxtthr: "链接现有的钱包",
      tradetctit: "选择代币",
      tradetctxty: "搜素代币或粘贴代币地址",
      tradetctxtt: "存入代币",
      tradetctxtthr: "开始交易",
    },

    en: {
      language: "English",
      Choose: "Please select language",
      continue: "continue",
      cjpassword:
        "Please create a password, including the following conditions",
      passwordshow: "show",
      inppassword: "password",
      cfinppassword: "Repeat password",
      passwordnone: "hide",
      passlist: ["8 characters", "capital", "number", "lower case"],
      policy: "Privacy Policy",
      policyend: "scroll to bottom",
      accept: "accept",
      terms: "Terms of Service",
      forget: "forget the password",
      forgetjs:
        "Within 24 hours after changing your password, you will not be able to withdraw money on the new device.",
      setpass: "reset Password",
      gologin: "Return to login",
      enteremail: "Enter your email address",
      emailjc: "Please check your email for a password reset link",
      connectti: "Stay connected with push notifications!",
      connectjs:
        "By enabling push notifications, you will receive important updates about your transactions, MoonDrop and other important alerts and news.",
      connectbuty: "enable",
      connectbutt: "Skip for now",
      setemali: "email",
      setusername: "username",
      changeemail: "Change email",
      changeusername: "Change username",
      changepassword: "Change password",
      setyy: "language",
      setterms: "terms",
      setpolicy: "policy",
      logout: "Sign out",
      removename: "Delete your account",
      forgetpass: "forget the password",
      setfh: "return",
      nativetitle: "Get native App",
      nativecon: "Sloppy on road apps",
      welcomebutone: "Login",
      welcomebuttwo: "start using",
      logintit: "Login",
      logintitt: "Sign up",
      loginemail: "e-mail",
      loginpass: "password",
      loginnonull: "password can not be blank",
      loginbut: "Login",
      loginforget: "Forgot password",
      registerti: "Let's start",
      registercont: "What's your e-mail address?",
      registeremailadd: "email address",
      registeremailtxt: "This email will be used to log in",
      usertit: "Create username",
      usertittxt: "Username will be used as your code to refer friends?",
      userplace: "Enter your user name",
      usercont:
        "The account name should be between 4 and 22 characters, consisting only of English letters and numbers",
      recommendtit: "Do you have a referral code?",
      recommendplace: "Referral code",
      recommendcon:
        "Get a referral code and get a $25 bonus to cover future expenses",
      recommendbutone: "Submit code",
      recommendbuttwo: "jump over",
      settitle: "Profile settings",
      changeemail: "Change email",
      changeemailcon:
        "You will not be able to withdraw funds using your new device for 24 hours after changing your email address.",
      changeemailplacey: "Enter new email address",
      changeemailplacet: "Enter your password",
      changeusertity: "Change email",
      changeuserplacey: "Enter your email",
      changeuserplacet: "Enter new username",
      changeusercon:
        "Username should be between 4 and 22 characters, consisting of English letters and numbers only",
      changepasstit: "change password",
      removeusertit: "This will delete your account",
      removeuserbutyi: "Yes, delete my account",
      removeuserbutt: "Cancel",
      hometit: "Position",
      homeck: "View transactions",
      hometime: "past 24 hours",
      hometaby: "1D",
      hometabw: "1Y",
      homepower: "purchasing power",
      homefory: "trade",
      homefort: "attack",
      homeforthr: "Pre-sale",
      homeforf: "Automatic DCA",
      homeforw: "options",
      homeforsix: "wallet",
      homethrti: "Active trading",
      homethrtype: "Type",
      homethrtypey: "profit",
      homethrtypet: "loss",
      homethrtypethr: "position",
      homethrtypef: "date",
      tradey: "market",
      tradet: "trade",
      tradethr: "index",
      tradeplace: "Search coins",
      tradeinptxt: "Paste",
      tradetoptxt: "All",
      tradeinptopy: "Name/Market value",
      tradeinptopt: "price/quantity",
      givemoney: "Give a friend $25",
      tradeethbuty: "to exchange",
      tradeethbutt: "limit order",
      tradetabty: "exchange",
      tradetabtwoy: "use. . . pay",
      tradetabtwoqc: "Clear",
      tradetabtwoye: "Balance",
      teadetabtwoxd: "Max limit",
      tradetabtwosd: "receive",
      tradetabtwoty: "purchase",
      tradetabtwott: "Sell",
      tradetabtwozf: "pay",
      tradetabtwoinpy: "buy at this price",
      tradetabtwoinpt: "quantity",
      tradetabtwoinpthr: "total amount",
      tradetabtwoinpf: "Benefited from",
      tradetabtwoinpw: "stop loss",
      tradetabtwoinpsix: "The order expiry date is",
      tradetabtwopy: "Market price: 1 WETH = 1796 USDT",
      tradetabtwopt: "Set trading strategy (take profit/stop loss)",
      tradetabtwobut: "Trading",
      tradetabthrtxt: "coming soon",
      attacktit: "attack trade",
      attacktaby: "sandwich",
      attacktabt: "SniperDEX LP",
      attackonetaby: "Token",
      attacktwotaby: "Set up",
      attackonetabt: "Position",
      attackonetabthr: "History",
      attackoneyabytxt: "Deposit code to start sandwich trading",
      attackoneyabttxt: "You have no active sandwich transactions",
      attackoneyabthrtxt: "Choose a token to start the attack. >",
      attackoneyabtatxt: "You don't have any sandwich history",
      attackoneyabthratxt: "Start sandwich>",
      attacktwobuty: "custom token",
      attacktwobutt: "Snipe all",
      attavktwoinpy: "search token",
      attavktwoinpt: "Paste",
      attacktwoinpp: "How many tokens are needed for a single sniper shot?",
      attacktwoinpt: "block delay",
      attacktwoinpthr: "Gas options",
      attackbotbut: "Confirm sniper automation",
      attacktwotabery: "You have no active sniping position.",
      attacktwotabert: "Choose a token to start sniping. >",
      attacktwotabethry: "You don't have any sniping history",
      attacktwotabthrt: "Start sniping>",
      ethree: "Fees owed",
      connectlistt: "Activity",
      connecttc: "Filter",
      connecttcly: {
        one: "All",
        two: "Trade",
        three: "Attack",
        four: "Pre-sale",
      },
      connecttclt: {
        one: "All",
        two: "To-do",
        three: "Fully",
        four: "Created",
        five: "Cancel",
        six: "Failure",
      },
      connectthr: "date",
      connectfour: "reset",
      connectfive: "Apply filter",
      connectsix: "extract",
      connectqi:
        " There is no activity for trading yet, you can view it this time",
      connectba: "withdraw",
      connectjiu: "Enter public address",
      earntit: "earn",
      earntaby: "recommender",
      earntabytop: "Available rewards",
      earntabytopt: "receive",
      earntabytxt: "Commission (pledge to increase commission rate)",
      earntabttxty: "pledge",
      earntabttxtt: "(coming soon)",
      earntabthrtxty: "Estimated revenue per 1 commission",
      earntabythr: "Invite friends",
      earnrabyfour: "invite",
      earnrabyfive: "award",
      earntabtyi: "your points",
      earntabter: "you are on the leaderboard",
      earntabtsan: "get promoted",
      earntabtfour: "Token empowerment",
      earntabtfive: "Complete today's daily tasks",
      earntabtsix: "Daily boost activation:",
      earntabtqi: "Mission promotion is activated:",
      earntabtba: "Total improvement:",
      earntabtjiu: "Inactive",
      earntabtten: "Accumulate points",
      earntabttenyi: "All points received",
      earntabttener: "Ranking list",
      earntabttensan: "you are",
      earntabttenfour: "username",
      earntabttenfive: "integral",
      walletti: "Enter your recovery phrase or private key",
      walletcon:
        "Your recovery phrase or private key is required to automate transactions - capital is at risk.",
      wallettxt: "How to find my recovery phrase",
      walletplace: "Or enter a recovery message",
      walletstit: "How would you like to add your wallet?",
      walletstxty: "Import wallet",
      walletstxtt: "respected",
      walletstxtthr:
        "Enter your recovery phrase or private key from another crypto wallet",
      walletttit: "Congratulations on your new crypto wallet!",
      walletttxty: "Give your wallet a nickname.",
      walletttxtt: "My wallet 1",
      walletttxtthr: "Your public address will be",
      walletttxtf: "save this wallet",
      porttxty: "Link your wallet to get started!",
      porttxtt: "Link a new wallet",
      porttxtthr: "Link existing wallet",
      tradetctit: "Select a token",
      tradetctxty: "Search for a coin or paste the coin address",
      tradetctxtt: "Deposit tokens",
      tradetctxtthr: "Start trading",
    },
  },
  mutations: {
    changeyy(state, str) {
      state.txt = state[str];
    },
  },
  actions: {
    // incrementAsync({ commit }) {
    //   setTimeout(() => {
    //     commit("increment");
    //   }, 1000);
    // },
  },
  getters: {},
});

export default store;
